on:
  push:
    branches:
      - main
  
jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read version from version.txt
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/aalbaker/supermario:${{ steps.version.outputs.VERSION }}'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
